services:
  pgdb:
      image: postgres
      container_name: vault_db
      environment:
        POSTGRES_DB: ${PG_DB_NAME}
        POSTGRES_USER: ${PG_USER}
        POSTGRES_PASSWORD: ${PG_PASSWORD}
      ports:
        - 5432:5432
      volumes:
        - pgdbdata:/var/lib/postgresql/data/
      restart: on-failure

volumes:
  pgdbdata: