"""empty message

Revision ID: 70022076dbeb
Revises: 8543d676f4d9
Create Date: 2025-10-25 11:17:36.346938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70022076dbeb'
down_revision: Union[str, Sequence[str], None] = '8543d676f4d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'meta')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
