"""empty message

Revision ID: 8543d676f4d9
Revises: 07714018741f
Create Date: 2025-10-08 10:54:16.209224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8543d676f4d9'
down_revision: Union[str, Sequence[str], None] = '07714018741f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodes', 'parent_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodes', 'parent_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
